/**
 * Gym Mingle User Profiles
 * 8+ deeply populated fitness-focused user profiles for NYC
 */

import { UserProfile } from "./types";

export const userProfiles: UserProfile[] = [
  {
    id: 1,
    name: "Jordan",
    age: 28,
    location: "Brooklyn, NY",
    imageUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=500&h=700&fit=crop",
    bio: "Yoga instructor with a passion for trail running and plant-based living. Love exploring hidden parks in NYC and trying new wellness studios.",
    motto: "Strong body, peaceful mind, adventurous spirit.",
    matchScore: 94,
    fitnessActivities: [
      { name: "Yoga", icon: "🧘‍♀️" },
      { name: "Trail Running", icon: "🏃‍♀️" },
      { name: "Pilates", icon: "💪" },
      { name: "Rock Climbing", icon: "🧗‍♀️" },
      { name: "Cycling", icon: "🚴‍♀️" },
    ],
    cuisinePreference: "Mediterranean & Vegan",
    dateVibe: "Adventurous & Mindful",
    spicyTier: "Adventurous",
  },
  {
    id: 2,
    name: "Alex",
    age: 31,
    location: "Manhattan, NY",
    imageUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=500&h=700&fit=crop",
    bio: "Fitness entrepreneur, CrossFit coach, and self-proclaimed food critic. Weekend mountain biker, coffee addict, looking for someone who matches my energy.",
    motto: "Lift heavy, eat well, live fully.",
    matchScore: 91,
    fitnessActivities: [
      { name: "CrossFit", icon: "🏋️" },
      { name: "Mountain Biking", icon: "🚵" },
      { name: "Swimming", icon: "🏊" },
      { name: "Boxing", icon: "🥊" },
      { name: "Soccer", icon: "⚽" },
    ],
    cuisinePreference: "Steakhouse & Italian",
    dateVibe: "Energetic & Social",
    spicyTier: "Spicy",
  },
  {
    id: 3,
    name: "Morgan",
    age: 26,
    location: "Park Slope, NY",
    imageUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=500&h=700&fit=crop",
    bio: "Pilates instructor and wellness coach. Obsessed with boutique fitness classes, outdoor concerts, and meaningful conversations over coffee.",
    motto: "Balance is key—fitness fuels everything.",
    matchScore: 88,
    fitnessActivities: [
      { name: "Pilates", icon: "💪" },
      { name: "Yoga", icon: "🧘‍♀️" },
      { name: "Barre", icon: "🩰" },
      { name: "Spinning", icon: "🚴" },
      { name: "Hiking", icon: "🥾" },
    ],
    cuisinePreference: "Healthy & Organic",
    dateVibe: "Relaxed & Authentic",
    spicyTier: "Adventurous",
  },
  {
    id: 4,
    name: "Casey",
    age: 29,
    location: "Williamsburg, NY",
    imageUrl: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=500&h=700&fit=crop",
    bio: "Skate culture enthusiast and street artist. Into underground fitness movements, vintage sneaker collecting, and late-night roller skating in the city.",
    motto: "Life's a freestyle—embrace the momentum.",
    matchScore: 92,
    fitnessActivities: [
      { name: "Skateboarding", icon: "🛹" },
      { name: "Roller Skating", icon: "🛼" },
      { name: "Parkour", icon: "🤸" },
      { name: "Street Basketball", icon: "🏀" },
      { name: "Breakdancing", icon: "💃" },
    ],
    cuisinePreference: "Brooklyn Street Food",
    dateVibe: "Edgy & Creative",
    spicyTier: "Extra Spicy",
  },
  {
    id: 5,
    name: "Taylor",
    age: 32,
    location: "Upper West Side, NY",
    imageUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=500&h=700&fit=crop",
    bio: "Marathon runner and triathlon competitor. Health-conscious consultant by day, endurance athlete on weekends. Love exploring Central Park and recovery spas.",
    motto: "The finish line is just another beginning.",
    matchScore: 89,
    fitnessActivities: [
      { name: "Marathon Running", icon: "🏃" },
      { name: "Triathlon", icon: "🏊" },
      { name: "Rowing", icon: "🚣" },
      { name: "Circuit Training", icon: "⚡" },
      { name: "Swimming", icon: "🏊" },
    ],
    cuisinePreference: "Asian Fusion",
    dateVibe: "Determined & Romantic",
    spicyTier: "Adventurous",
  },
  {
    id: 6,
    name: "Quinn",
    age: 27,
    location: "Astoria, NY",
    imageUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=500&h=700&fit=crop",
    bio: "Rock climbing coach and outdoor instructor. Weekend rope adventures in the Catskills, weekday gym sessions at Brooklyn Boulders. Coffee enthusiast.",
    motto: "Life's about climbing higher and seeing further.",
    matchScore: 90,
    fitnessActivities: [
      { name: "Rock Climbing", icon: "🧗" },
      { name: "Boulder Climbing", icon: "🧗‍♀️" },
      { name: "Rappelling", icon: "⛰️" },
      { name: "Yoga", icon: "🧘" },
      { name: "Trail Running", icon: "🏃" },
    ],
    cuisinePreference: "Farm-to-Table",
    dateVibe: "Adventurous & Intense",
    spicyTier: "Spicy",
  },
  {
    id: 7,
    name: "Riley",
    age: 24,
    location: "East Village, NY",
    imageUrl: "https://images.unsplash.com/photo-1516534775068-bb57a52f5b43?w=500&h=700&fit=crop",
    bio: "Dancer and choreographer. Ballet, contemporary, street dance—fitness meets art for me. Love boutique studios and exploring dance communities.",
    motto: "Movement is the poetry of the body.",
    matchScore: 87,
    fitnessActivities: [
      { name: "Ballet", icon: "🩰" },
      { name: "Contemporary Dance", icon: "💃" },
      { name: "Pilates", icon: "💪" },
      { name: "Spinning", icon: "🚴" },
      { name: "Stretching/Yoga", icon: "🧘" },
    ],
    cuisinePreference: "Japanese & Sushi",
    dateVibe: "Artistic & Playful",
    spicyTier: "Extra Spicy",
  },
  {
    id: 8,
    name: "Sam",
    age: 30,
    location: "Tribeca, NY",
    imageUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=500&h=700&fit=crop",
    bio: "Wellness entrepreneur and fitness tech founder. Into biohacking, cold plunges, and optimizing everything. Looking for someone into personal growth.",
    motto: "Optimize, elevate, dominate.",
    matchScore: 93,
    fitnessActivities: [
      { name: "HIIT Training", icon: "⚡" },
      { name: "Cold Plunge", icon: "🧊" },
      { name: "Strength Training", icon: "🏋️" },
      { name: "Sauna Recovery", icon: "🔥" },
      { name: "Meditation", icon: "🧘" },
    ],
    cuisinePreference: "Keto & Protein-Focused",
    dateVibe: "Intellectual & Intense",
    spicyTier: "Spicy",
  },
  {
    id: 9,
    name: "Harper",
    age: 28,
    location: "Greenpoint, NY",
    imageUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=500&h=700&fit=crop",
    bio: "Fitness instructor and creative director. Marathon runner on weekends, boutique studio devotee. Into sustainable fashion and wellness culture.",
    motto: "Strong is beautiful, kind is everything.",
    matchScore: 91,
    fitnessActivities: [
      { name: "Marathon Running", icon: "🏃" },
      { name: "Boutique Classes", icon: "💪" },
      { name: "Yoga", icon: "🧘" },
      { name: "Hiking", icon: "🥾" },
      { name: "Cycling", icon: "🚴" },
    ],
    cuisinePreference: "Plant-Based & Raw",
    dateVibe: "Creative & Wellness-Focused",
    spicyTier: "Vanilla",
  },
];
